### ISSUE TITLE
Fitting Double Exponential

### ISSUE THREAD

**Issue by ramess101** [MaginnGroup/LammpsPostAnalysis#1]
@zhangyongND 

We are implementing the same viscosity approach in our research (https://github.com/ramess101/IFPSC_10/issues). Specifically, we are fitting the average of numerous replicates to a double exponential function with a weighted optimization, where the weights are determined by the standard deviation. We use the same heuristic for the long time cut-off (40% x eta_infinity) and exclude short-time data from the fit (less than 3 ps).

For the most part, this method has worked very well for us. However, on occasion (typically for slower dynamics, more viscous systems), the optimizer does not actually find the best fit to the double exponential. It is pretty obvious when the fitting procedure has failed, as the best fit does not even resemble the data. To overcome this issue we have tried providing several different guesses, but this has become more of an art than a science as there is no clear intuition as to what a "good" guess should be.

I noticed that the primary difference between our implementation and yours is that we are using scipy.optimize.minimize, whereas your fitvisc.py code uses scipy.optimize.curve_fit on line 30. It would not take much effort to substitute minimize with curve_fit in our code. But before trying that, I wanted to see if you have run into this problem yourself. If so, how did you handle it? And does curve_fit find a good fit almost every time?

**Comment by mike5603** [comment]
I have noticed the same dependence on initial guess for parameters in curve_fit. I do not think that the changing the fitting procedure would help with this. My technique for this is the same as yours, where I just change the initial guess to see if I can get a better fit. 

One benefit to using curve_fit is that it also outputs the covariance matrix, which could be used to provide an estimate of the error for the fit. If you wanted to automate this procedure, you could have multiple initial guesses of the parameters and then compare the quality of the fits using the covariance matrix to determine the best fit.

**Comment by ramess101** [comment]
@mike5603 

Thank you for the response.

OK, it is good to know that curve_fit is not a panacea and that other people have had the same issue. As far as using the covariance matrix to quantify uncertainties, due to the non-linear nature of this optimization, we actually use bootstrap re-sampling to quantify the error. This works quite well. In my experience, covariance matrices can give misleading uncertainties for highly non-linear optimizations. Do your uncertainties usually look reasonable using the covariance matrix?

**Comment by mike5603** [comment]
We actually tend to do something more similar to the bootstrapping method. The covariance matrix idea was just to get a quick estimate of error to try and determine the quality of the fit. Thinking about it more, this would not actually be a good descriptor for the quality of the fit. It would be easier and better to just look at the values of the target function to determine the relative quality of the fits, which would probably be easier with your method.

**Comment by ramess101** [comment]
@mike5603 

Alright, that makes sense. Thanks again for helping clarify this issue.
